apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-image-volume
          persistentVolumeClaim:
            claimName: todo-claim
      containers:
      - name: todo-app
        image: diing54/todo-app:v5
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: todo-image-volume
          mountPath: /usr/src/app/images
