apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-deployment
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong
        image: diing54/ping-pong:v4
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 3000
